Added count to username if present
JMAConsulting/biz.jmaconsulting.aoservicelisting pull request #79
Opened 2020-05-27 11:07 UTC by Edzelopez

2020-05-28 08:41 UTC, seamuslee001 commented on aoservicelisting.civix.php
> +    $query = $con->select('users_field_data', 'u')
is $con defined? @Edzelopez ?

2020-05-28 08:49 UTC, seamuslee001 requested changes
I think you need to fix the $con variable

2020-05-28 08:53 UTC, Edzelopez commented on aoservicelisting.civix.php
> +    $query = $con->select('users_field_data', 'u')
Whoops, fixed it.

2020-06-01 08:06 UTC, seamuslee001 approved these changes

2020-06-01 08:06 UTC, seamuslee001 commented
Looks fine to me now @Edzelopez

2020-06-01 09:44 UTC, merged